### ISSUE TITLE
Support for STL containers in interface file

### ISSUE THREAD

**Issue by varunagrawal** [borglab/wrap#10]
It would be great to have direct STL support in the interface file so we can bind functions and instance variables like:
```cpp
class SfmTrack {
  std::vector<std::pair<size_t, gtsam::Point2>> measurements;
};
```

This is straightforward via the Pybind wrapper, and involves 2 parts:

1. Declare opaque types for two-way data propagation.

```cpp
using SfmMeasurement = std::pair<size_t, gtsam::Point2>;
PYBIND11_MAKE_OPAQUE(std::vector<SfmMeasurement>);
```
2. Bind STL container inside the module.

```cpp
py::bind_vector<std::vector<std::pair<size_t, gtsam::Point2>>>(m_, "SfmMeasurements");

// Already added by interface parser
py::class_<gtsam::SfmTrack, boost::shared_ptr<gtsam::SfmTrack>>(m_, "SfmTrack")
...
```

Unfortunately, my understanding of the interface parser isn't excellent so it is taking me too long to figure it out and make the changes. Adding documentation to the interface parser would also be super nice.

**Comment by varunagrawal** [comment]
So this feature seems to be already implemented, but we need to add documentation for it.

**Comment by ProfFan** [comment]
It's because the Python wrapper just ignores the type declaration lol, because pybind11 handles it.

**Comment by dellaert** [comment]
@ProfFan so please document
