### ISSUE TITLE
write pybind "source code" directly in `.i` file

### ISSUE THREAD

**Issue by gchenfc** [borglab/wrap#103]
I suspect this might have opposition, but sometimes I feel that it would be easier for some obscure feature to just write the pybind code directly rather than update wrap to support a new feature.  For example, if we want to add some obscure feature like [Keyword-only arguments](https://pybind11.readthedocs.io/en/stable/advanced/functions.html#keyword-only-arguments) then we might find it easier to just directly type
```c++
m_.def("f", [](int a, int b) { /* ... */ },
      py::arg("a"), py::kw_only(), py::arg("b"));
```
rather than add the feature into wrap and figure out some syntax for it that will only be used once in the lifetime of wrap.

Therefore, I would propose something similar to how in C++ you can use `extern "C" { ... }` or `asm( ... );` to directly write C or assembly code.  The analog in a .i file might be something like:
```c++
class MyClass {
  void func();
};

PYBIND {
  m_.def("f", [](int a, int b) { /* ... */ },
      py::arg("a"), py::kw_only(), py::arg("b"));
}
```

which would generate
```c++
PYBIND11_MODULE(class_py, m_) {
    py::class_<MyClass, std::shared_ptr<MyClass>>(m_, "MyClass")
        .def(py::init<>())
        .def("func",[](MyClass* self){return self->func();})

    m_.def("f", [](int a, int b) { /* ... */ },
      py::arg("a"), py::kw_only(), py::arg("b"));
}
```

As an extension, we could potentially maybe even endow it with python string format replacement, so for example
```c++
PYBIND {
  {module_name}.def("f", [](int a, int b) { /* ... */ },
      py::arg("a"), py::kw_only(), py::arg("b"));
}
```
and during parsing, we could pass this string with all the relevant kwargs like `module_name`, `class_name`, `namespace`, `prefix`, `suffix`, etc.  This is more iffy since then all the other characters have to be escaped properly, e.g. `{` has to change to `{{` which would be annoying, but might be useful in case any variable naming conventions change.

Matlab wrapper would just ignore this block, obviously.

Thoughts?

@varunagrawal @ProfFan

**Comment by varunagrawal** [comment]
What's the use case? And more importantly, this would potentially break compatibility with other languages. If we decide to support swift tomorrow, we now need to have ignore blocks for Pybind specific code which will be annoying to maintain and defeats the whole purpose of this project.

**Comment by dellaert** [comment]
I'm opposed. Adds complexity for niche case, and non-negligable maintenance cost.
