### ISSUE TITLE
pyparsing install needed?

### ISSUE THREAD

**Issue by dellaert** [borglab/wrap#130]
So, I just tried to rebuild gtsam on an older system, and it threw errors until I did "pip install pyparsing". I think that should not be required, right? Did something change from before?

**Comment by varunagrawal** [comment]
pyparsing is needed if wrapping is enabled. It should be optional otherwise. We can look at this a bit later I guess?

**Comment by varunagrawal** [comment]
This PR https://github.com/borglab/gtsam/pull/1628 should resolve this. Closing, please reopen if still an issue.
