### ISSUE TITLE
MATLAB Toolbox Memory Leak

### ISSUE THREAD

**Issue by mattking-smith** [borglab/wrap#133]
## Description
There appears to be a memory leak when wrapping GTSAM into the MATLAB environment. MATLAB fails to release memory back to the computer after running and clearing GTSAM related code and variables. 

Eventually user is forced to close and reopen MATLAB before memory is completely consumes (RAM + SWAP if using Linux).

I believe I mentioned this in another MATLAB pointer issue some time ago: _Originally posted by @mattking-smith in https://github.com/borglab/wrap/issues/48#issuecomment-805995726_
## Steps to reproduce
1. Install [GTSAM + MATLAB toolbox](https://github.com/borglab/gtsam)
2. In the MATLAB environment attempt the following:
> `cd /Users/yourname/toolbox  % Change to wherever you installed the toolbox`
> `cd gtsam_examples           % Change to the examples directory`
3. Run RangeSLAMExample_plaza.m file, for example.

## Observed behavior
Upon opening MATLAB we start with the following memory consumption:
![image](https://user-images.githubusercontent.com/12990760/145230824-947b59a9-88f9-4756-938b-1ba3c0526833.png)

Running the RangeSLAMExample_plaza.m file in MATLAB results in successful execution of the code:
```
>> RangeSLAMExample_plaza
Elapsed time is 28.812783 seconds.
Elapsed time is 16.735759 seconds.
```
However, calling `clear` or `clear all` in the MATLAB command window does not free memory. 

Output of memory after calling `>> clear; clear all;` in command window:
![image](https://user-images.githubusercontent.com/12990760/145232154-52063518-60c3-448f-aa3e-54f5487b9458.png)

We can see that MATLAB is holding ~60% of the system memory. Only method I have found for freeing memory from MATLAB is to close and open a new session.

## Suggested Solutions
Does the solution to this problem still lie in the `matlab_wrapper.py` file, as mentioned by @varunagrawal?:
_Originally posted by @varunagrawal in https://github.com/borglab/wrap/issues/48#issuecomment-806204007_

## Environment
Problem reproduced on 2 different Linux computers:
Linux OS: Ubuntu 20.04
MATLAB version: 2021a and 2020b
Standard GTSAM + MATLAB Toolbox build.

**Comment by varunagrawal** [comment]
Wouldn't you have to use `clear mex;` in this case?

**Comment by mattking-smith** [comment]
> Wouldn't you have to use `clear mex;` in this case?

Just tried `clear mex` to no avail.

**Comment by mattking-smith** [comment]
> Wouldn't you have to use `clear mex;` in this case?

This was the output of a `clear mex`:
```
>> clear mex
WARNING:  Wrap modules with variables in the workspace have been reloaded due to
calling destructors, call 'clear all' again if you plan to now recompile a wrap
module, so that your recompiled module is used instead of the old one.
```

**Comment by varunagrawal** [comment]
Yeah that's normal. That message is generated by us as a notification to the user.

The main point though: did the memory issue get resolved?

**Comment by mattking-smith** [comment]
> Yeah that's normal. That message is generated by us as a notification to the user.
> 
> The main point though: did the memory issue get resolved?

That is a negative.

**Comment by mattking-smith** [comment]
> Yeah that's normal. That message is generated by us as a notification to the user.
> 
> The main point though: did the memory issue get resolved?

Has anyone else been able to reproduce this memory leak issue?

**Comment by varunagrawal** [comment]
Some new thoughts on this because I understand the wrapper much better now:

1. As @ProfFan & @dellaert mentioned in #48  we have a function called `_deleteAllObjects` whose job is to delete all the objects created. This function is registered to `MexAtExit` so it will only run when the user calls `clear mex;`.
2. Each class defined in the wrapper has a corresponding destructor method. For example:
	
```matlab
classdef ClassD < handle
  properties
    ptr_ClassD = 0
  end
  methods
    function delete(obj)
      namespaces_wrapper(25, obj.ptr_ClassD);
    end

    function display(obj), obj.print(''); end
    %DISPLAY Calls print on the object
    function disp(obj), obj.display; end
    %DISP Calls print on the object
  end

end
```

which in turn calls the underlying C++ function:
```cpp
void ClassD_deconstructor_25(int nargout, mxArray *out[], int nargin, const mxArray *in[])
{
  typedef boost::shared_ptr<ClassD> Shared;
  checkArguments("delete_ClassD",nargout,nargin,1);
  Shared *self = *reinterpret_cast<Shared**>(mxGetData(in[0]));
  Collector_ClassD::iterator item;
  item = collector_ClassD.find(self);
  if(item != collector_ClassD.end()) {
    delete self;
    collector_ClassD.erase(item);
  }
}
```

If there is an issue with the deallocation, it will be somewhere here.

@mattking-smith you mentioned you are familiar with writing Mex files. In this case, one simple way to move forward is to pick a class that causes memory leakage (such as from an example you ran), pull up the .m file corresponding to that class and look at the number being passed to gtsam_wrapper for that classes `delete` method. That number is the id that will point you to the corresponding destructor in the `gtsam_wrapper.cpp` file.
You should then really understand what is going on there and why the memory leak is happening. Is the delete function not doing the right thing? Is there something we are missing? If you had to hand-write that mex file, how would you do it?

Once we have that info, we can incorporate that into the wrapper and resolve this issue permanently. :slightly_smiling_face:

**Comment by mattking-smith** [comment]
> That number is the id that will point you to the corresponding destructor in the `gtsam_wrapper.cpp` file.

@varunagrawal where is this 'gtsam_wrapper.cpp` file located? 

I have identified the class definition for the NonlinearFactorGraph (defined in NonlinearFactorGraph.m) as the following:
```
classdef NonlinearFactorGraph < handle
  properties
    ptr_gtsamNonlinearFactorGraph = 0
  end
  .
  .
  .
  methods
    function delete(obj)
      gtsam_wrapper(1542, obj.ptr_gtsamNonlinearFactorGraph);
    end
end
```
but I cannot find where the 'gtsam_wrapper.cpp` file located. Is it in the wrap repository?

**Comment by varunagrawal** [comment]
It's a generated file. It should be in `build/wrap/gtsam/`.

**Comment by mattking-smith** [comment]
After looking around, I believe I have found a place we can start working off of for developing memory leak-free code. 

I have downloaded and tested the example MATLAB class wrapper for a C++ class given in his [Mathworks file exchange](https://www.mathworks.com/matlabcentral/fileexchange/38964-example-matlab-class-wrapper-for-a-c-class).

The package provides an example of how to wrap a C++ class in a MATLAB class, via a mex interface, safely, without memory leaks, whilst achieving an interface in MATLAB that is similar to the underlying C++ interface.

I note that their handling of C++ classes are slightly different than our implementation. 

I will try and take a look at testing if we can import GTSAM by this method.

**Comment by varunagrawal** [comment]
Who is his?

**Comment by mattking-smith** [comment]
> Who is his?

[Oliver Wood](https://www.mathworks.com/matlabcentral/profile/authors/1073021)

**Comment by mattking-smith** [comment]
@varunagrawal does this bug need to elevated to high-priority status? Or is not appropriate to hold of the [4.1 release](borglab/gtsam#824)?

**Comment by mattking-smith** [comment]
@varunagrawal if I wanted to implement memory allocation similar this comment:
> I have downloaded and tested the example MATLAB class wrapper for a C++ class given in his [Mathworks file exchange](https://www.mathworks.com/matlabcentral/fileexchange/38964-example-matlab-class-wrapper-for-a-c-class).

then would I start making these edits in the [matlab.h](https://github.com/borglab/wrap/blob/master/matlab.h#L385-L466)? Possibly at the following lines?:
https://github.com/borglab/wrap/blob/24897186873c92a32707ca8718f7e7b7dbffc589/matlab.h#L385-L466

**Comment by dellaert** [comment]
Matt, I’m not in favor of starting with a new memory allocation method unless you can pinpoint what is wrong with the old one. Not understanding the current wrapper is not a reason to refactor in my humble opinion :-) Re-reading the thread, the only thing you said was “it is quite different“; That doesn’t seem to be an argument that the old method is wrong or broken.

Note I very much appreciate you looking into it, but I would rather make the minimal change to fix what’s wrong, if we can figure out what is wrong. If not, and we have to radically change, it will have to come with an explanation of how the old wrapper is broken, and how the new approach will fix it.

**Comment by varunagrawal** [comment]
Sorry for the delay in responding. I agree with Frank in that we should identify what are we currently doing that is causing the issue. @mattking-smith I can have a pair-programming session with you later today to figure this out.

**Comment by mattking-smith** [comment]
> Sorry for the delay in responding. I agree with Frank in that we should identify what are we currently doing that is causing the issue. @mattking-smith I can have a pair-programming session with you later today to figure this out.

Let me know when is good for you. Perhaps we can schedule a BlueJeans sessions?

**Comment by varunagrawal** [comment]
@mattking-smith and I are looking at `gtsamPose2_deconstructor_592` as a small example case to debug the matlab wrapper memory leak issue.

1. We looked at the example from Oliver Woodford to understand the correct paradigms and idions used for deletion.
2. Check if is this a valid conversion from mxArray to the class type: `Shared *self = *reinterpret_cast<Shared**>(mxGetData(in[0]));`
3. Need to understand what is happening in `collector_gtsamPose2`.
4. `collector_gtsamPose2` basically is a global variable of type set that stores shared_ptrs to all the instances of Pose2. This is done so that when `clear mex;` or its equivalent is called (e.g. matlab shutsdown), then the `_deleteAllObjects` function can just go through all the pointers in the collector and delete them.
5. If we do destructor handling correctly (i.e. move `delete self` outside the if-block), then we may not need to use the collectors since we won't need the `_deleteAllObjects` function anymore. Matlab should be able to clear the objects at its own level rather than at the Mex/C++ level.

**Comment by mattking-smith** [comment]
> @mattking-smith and I are looking at `gtsamPose2_deconstructor_592` as a small example case to debug the matlab wrapper memory leak issue.
> 
> 1. We looked at the example from Oliver Woodford to understand the correct paradigms and idions used for deletion.
> 2. Check if is this a valid conversion from mxArray to the class type: `Shared *self = *reinterpret_cast<Shared**>(mxGetData(in[0]));`
> 3. Need to understand what is happening in `collector_gtsamPose2`.
> 4. `collector_gtsamPose2` basically is a global variable of type set that stores shared_ptrs to all the instances of Pose2. This is done so that when `clear mex;` or its equivalent is called (e.g. matlab shutsdown), then the `_deleteAllObjects` function can just go through all the pointers in the collector and delete them.
> 5. If we do destructor handling correctly (i.e. move `delete self` outside the if-block), then we may not need to use the collectors since we won't need the `_deleteAllObjects` function anymore. Matlab should be able to clear the objects at its own level rather than at the Mex/C++ level.

I looked into changing the [wrapper.py](https://github.com/borglab/wrap/blob/master/gtwrap/matlab_wrapper/wrapper.py) such that the following code: https://github.com/borglab/wrap/blob/086be59bed87cc8a9c3f28b4cb99566b59bc3fda/gtwrap/matlab_wrapper/wrapper.py#L1264-L1274

 changes to             

```
elif collector_func[2] == 'deconstructor':
                body += textwrap.indent(textwrap.dedent('''\
                    typedef boost::shared_ptr<{class_name_sep}> Shared;
                    checkArguments("delete_{class_name}",nargout,nargin,1);
                    Shared *self = *reinterpret_cast<Shared**>(mxGetData(in[0]));
                    Collector_{class_name}::iterator item;
                    item = collector_{class_name}.find(self);
                    if(item != collector_{class_name}.end()) {{
                      collector_{class_name}.erase(item);
                    }}
                     delete self;
```
yet still do not see MATLAB releasing memory.

So we need to keep investigating @varunagrawal
