### ISSUE TITLE
Matlab default arguments

### ISSUE THREAD

**Issue by gchenfc** [borglab/wrap#134]
This is the "correct fix" for https://github.com/borglab/gtsam/issues/954.  Needed by @mattking-smith 

Notice, for example, that in the unit tests, the default argument tests are actually not correct.  For example,

https://github.com/borglab/wrap/blob/24897186873c92a32707ca8718f7e7b7dbffc589/tests/expected/matlab/DefaultFuncInt.m#L1-L6

This should be something more like

```matlab
function varargout = DefaultFuncInt(varargin)
      if length(varargin) == 2 && isa(varargin{1},'numeric') && isa(varargin{2},'numeric')
        functions_wrapper(8, varargin{:});
      else if length(varargin) == 1 && isa(...)
        ...
      else if length(varargin) == 0
        ...
      else
        error('Arguments do not match any overload of function DefaultFuncInt');
      end
```

**Comment by varunagrawal** [comment]
Aha you are correct sir. Good call.
