### ISSUE TITLE
Markdown Support (and other formats)

### ISSUE THREAD

**Issue by dellaert** [borglab/wrap#138]
It turns out it’s much easier to make a a notebook display pretty things than I thought! See https://ipython.readthedocs.io/en/stable/config/integrating.html

Basically, we just need a `_ipython_display_()` method, which can output valid markdown or even svg.

We could add that by having a display method in C++, and specially handled by the python wrapper. maybe there is similar functionality in MATLAB? @mattking-smith 

if I want to add that, what would I do? Where would I start?

**Comment by varunagrawal** [comment]
I guess we'd basically have to add a method to each class so this would be in `_wrap_method` in `pybind_wrapper.py`.

**Comment by dellaert** [comment]
Thanks, I'll take a look.

**Comment by varunagrawal** [comment]
Okay I got a version working, but as you mentioned, we will have to define a custom function in C++ called `display` or something.

What concerns me is that to output in a notebook, the `_ipython_display_` method needs to use a `display` method. An example can be found [here](https://notebook.community/rdhyee/webtech-learning/notebooks/Using%20_ipython_display_).

**Comment by dellaert** [comment]
Hey, I’m working on this. If you’re working on this, let’s coordinate please :-)

**Comment by varunagrawal** [comment]
Yes of course. Do you want to create a draft PR that I can review/add onto?

**Comment by dellaert** [comment]
Maybe we could chat briefly tomorrow or Monday.

**Comment by varunagrawal** [comment]
Sure thing, whatever you'd prefer.

**Comment by varunagrawal** [comment]
I also want to talk about progress on the hybrid factors. If I can help with the math or anything in terms of prep. I'm pretty pumped to get that working.

**Comment by dellaert** [comment]
I think hybrid branch could be ready for a PR, once there is a unit test?

**Comment by varunagrawal** [comment]
This was fixed with #142
