### ISSUE TITLE
Template support for free functions in the wrapper

### ISSUE THREAD

**Issue by swarrier246** [borglab/wrap#14]
## Feature

Template support for free functions in wrapper

## Motivation

Functions like triangulatePoint3, which can take different calibrations as arguments, currently require multiple copy-paste operations to add wrapper support for different calibrations.  

## Pitch

Adding template support for free functions allows gtsam to better be DRY.

**Comment by ProfFan** [comment]
Yup, I agree.

**Comment by dellaert** [comment]
Does that not work yet? It would be nice :-)

**Comment by ProfFan** [comment]
Let me investigate after finishing last project :)

**Comment by varunagrawal** [comment]
I'll take over this one. Should be straightforward.
