### ISSUE TITLE
Built in source

### ISSUE THREAD

**Issue by dellaert** [borglab/wrap#42]
why are we building *inside* the source directory? Can we change that? I think nothing should be added or subtraced inside source. If I make a special build folder, this is where I expect the python toolbox artifacts tk end up :-)
(think about having multiple build folders, which I definitely do sometimes - debug/release, now ARM vs x86)

**Comment by dellaert** [comment]
Maybe this is now happening - it could have been old artifacts I found inside my build folder. Advise @varunagrawal ? @ProfFan ?

**Comment by varunagrawal** [comment]
Interesting. I think I did that as a shortcut in the past, but I didn't update it in time. I'll get it fixed tomorrow.

**Comment by varunagrawal** [comment]
Looked into this today morning. The issue is specific to GTDynamics and independent of `wrap`. I am closing this since I have already added the fix to GTDynamics but we can re-open if the issue still persists.
