### ISSUE TITLE
Operator overloads in python?

### ISSUE THREAD

**Issue by dellaert** [borglab/wrap#58]
Do we have that?

I got this error:

```
TypeError: unsupported operand type(s) for *: 'gtsam.gtsam.Pose2' and 'gtsam.gtsam.Pose2'
```

:-)

**Comment by ProfFan** [comment]
I don't think we have operators implemented yet, but I think it's possible to implement (there is documentation in pybind11)

**Comment by varunagrawal** [comment]
https://pybind11.readthedocs.io/en/stable/advanced/classes.html#operator-overloading
