### ISSUE TITLE
CMAKE_PREFIX_PATH

### ISSUE THREAD

**Issue by gchenfc** [borglab/wrap#71]
In build/install/lib/cmake/gtwrap/gtwrapConfig.cmake, #68  changed `add_subdirectory(${CMAKE_INSTALL_FULL_LIBDIR}/gtwrap/pybind11 pybind11)` to instead use `GTWRAP_LIBDIR ` which is set to `CMAKE_PREFIX_PATH`, but it should actually be taking wrap's cmake install path instead of `CMAKE_PREFIX_PATH` which is for the _new_ project _being_ wrapped.

I guess this would be something like
```cmake
  set(GTWRAP_BINDIR ${GTWRAP_DIR}/../../../bin)
  set(GTWRAP_LIBDIR ${GTWRAP_DIR}/../../../lib")
  set(GTWRAP_INCLUDEDIR ${GTWRAP_DIR}/../../../include")
```

**Comment by ProfFan** [comment]
This should be set by gtwrapConfig and checked if exist here. I think I have already done that so maybe @varunagrawal changed it?
